apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZMkYwYVc1aGNHOXJaVHBuYUhCZmQySktUVVV3ZFd4d2ExQjFXVkZrY1ZkNFFqbHVhVmxGVlhCU1VqTXhNRUZHY2pVMCIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
