@startuml
title Cinema Abyss Container Diagram

top to bottom direction
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml


Person(User, "User", "A user of Cinema Abyss system")

System_Ext(RecommendationSystem, "Recommendation System", "(RabbitMQ) System recommends movies to users")
System_Ext(PaymentSystem, "Payment System", "(REST API) System handles payments for users")
System_Ext(OnlineStreamingService, "Online Cinema Streaming Service", "(REST API) System handles online streaming of movies")
System_Ext(FileStorage, "S3 File Storage", "System stores movies and other files")

System_Boundary(CinemaAbyss, "Cinema Abyss System") {
  Container(MobileApp, "Mobile App", "Swift", "User interface for mobile devices")
  Container(WebApp, "Web Application", "Vue.js", "User interface for web devices")
  Container(StandaloneApp, "Standalone App", "React Native", "User interface for standalone devices")

  Container(APIGateway, "API Gateway", "Golang", "Single point of entry for clients to access the system")

  Container(AuthService, "Auth Service", "Golang", "Handles authentication and authorization, emission tokens")
  ContainerDb(AuthDatabase, "Auth database", "PostgreSQL", "Stores user data, roles and bindings")

  Container(CatalogService, "Catalog Service", "Golang", "Handles catalog of movies")
  ContainerDb(CatalogDatabase, "Catalog Database", "PostgreSQL", "Stores catalog of movies")

  Container(MetadataService, "Metadata Service", "Golang", "Handles metadata of movies")
  ContainerDb(MetadataDatabase, "Metadata Database", "PostgreSQL", "Stores metadata of movies")

  Container(RecommendationService, "Recommendation Service", "Golang", "Handles recommendation of movies")
  ContainerDb(RecommendationDatabase, "Recommendation Database", "PostgreSQL", "Stores recommendation of movies")

  Container(PaymentService, "Payment Service", "Golang", "Handles payments for movies")
  ContainerDb(PaymentDatabase, "Payment Database", "PostgreSQL", "Stores payments for movies")

  Container(StreamingProxy, "Streaming Proxy", "Golang", "Handles online streaming of movies")
  ContainerDb(StreamingProxyDatabase, "Streaming Proxy Database", "PostgreSQL", "Stores online streaming of movies")
}

Rel(User, MobileApp, "Uses Mobile App to access the system")
Rel(User, WebApp, "Uses Web App to access the system")
Rel(User, StandaloneApp, "Uses Standalone App to access the system")

Rel(WebApp, APIGateway, "Uses API Gateway to access the system")
Rel(MobileApp, APIGateway, "Uses API Gateway to access the system")
Rel(StandaloneApp, APIGateway, "Uses API Gateway to access the system")

Rel(APIGateway, AuthService, "Register user, request token, set house and roles, register hub to house")
Rel(APIGateway, MetadataService, "Forwards requests to Metadata Service")
Rel(APIGateway, CatalogService, "Forwards requests to Catalog Service")
Rel(APIGateway, PaymentService, "Forwards requests to Payment Service")
Rel(APIGateway, StreamingProxy, "Forwards requests to Streaming Proxy")

Rel(CatalogService, SubscriptionService, "Checks subscription status of user")
Rel(CatalogService, RecommendationService, "Requests recommendation of movies")

Rel(AuthService, AuthDatabase, "Read/writes user data, roles and bindings")
Rel(MetadataService, MetadataDatabase, "Read/writes metadata of movies")
Rel(RecommendationService, RecommendationDatabase, "Read/writes recommendation of movies")
Rel(PaymentService, PaymentDatabase, "Read/writes payments for movies")
Rel(StreamingProxy, StreamingProxyDatabase, "Read/writes online streaming of movies")
Rel(CatalogService, CatalogDatabase, "Read/writes catalog of movies")

Rel(StreamingProxy, FileStorage, "Stream movies")
Rel(StreamingProxy, OnlineStreamingService, "Stream movies to users")

Rel(PaymentService, PaymentSystem, "Send payments requests")
Rel(RecommendationService, RecommendationSystem, "Send recommendation requests")
@enduml